In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from collections import Counter

# Load dataset
iris = sns.load_dataset("iris"

# Features and target
X = iris.drop("species", axis=1).values
y = iris["species"].values

# Train-test split (manual, 80-20)
np.random.seed(42)
indices = np.arange(len(X))
np.random.shuffle(indices)

split = int(0.8 * len(X))
train_idx, test_idx = indices[:split], indices[split:]

X_train, y_train = X[train_idx], y[train_idx]
X_test, y_test = X[test_idx], y[test_idx]
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))
def knn_predict(X_train, y_train, x_test, k=5):
    # Compute distances to all training points
    distances = [euclidean_distance(x_test, x_train) for x_train in X_train]
    
    # Get indices of k nearest neighbors
    k_indices = np.argsort(distances)[:k]
    
    # Get their labels
    k_labels = [y_train[i] for i in k_indices]
    
    # Majority vote
    most_common = Counter(k_labels).most_common(1)[0][0]
    return most_common
y_pred = [knn_predict(X_train, y_train, x, k=5) for x in X_test]
def accuracy(y_true, y_pred):
    return np.sum(y_true == np.array(y_pred)) / len(y_true)

print("Accuracy:", accuracy(y_test, y_pred))
def confusion_matrix(y_true, y_pred, labels):
    matrix = np.zeros((len(labels), len(labels)), dtype=int)
    label_to_index = {label: i for i, label in enumerate(labels)}
    
    for true, pred in zip(y_true, y_pred):
        matrix[label_to_index[true]][label_to_index[pred]] += 1
    return matrix

labels = np.unique(y)
cm = confusion_matrix(y_test, y_pred, labels)
print("Confusion Matrix:\n", cm)
def precision_recall_f1(cm):
    metrics = {}
    for i, label in enumerate(labels):
        tp = cm[i,i]
        fp = cm[:,i].sum() - tp
        fn = cm[i,:].sum() - tp
        precision = tp / (tp + fp) if (tp+fp) > 0 else 0
        recall = tp / (tp + fn) if (tp+fn) > 0 else 0
        f1 = 2*precision*recall / (precision+recall) if (precision+recall) > 0 else 0
        metrics[label] = {"precision": precision, "recall": recall, "f1": f1}
    return metrics

print("Metrics:", precision_recall_f1(cm))

Accuracy: 0.9666666666666667
Confusion Matrix:
 [[ 7  0  0]
 [ 0 11  0]
 [ 0  1 11]]
Metrics: {'setosa': {'precision': np.float64(1.0), 'recall': np.float64(1.0), 'f1': np.float64(1.0)}, 'versicolor': {'precision': np.float64(0.9166666666666666), 'recall': np.float64(1.0), 'f1': np.float64(0.9565217391304348)}, 'virginica': {'precision': np.float64(1.0), 'recall': np.float64(0.9166666666666666), 'f1': np.float64(0.9565217391304348)}}
