In [60]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

df = pd.read_csv("dataset.csv")

# Automatically detect feature columns (all columns except 'Y')
X = df.iloc[:, :-1].values   # all rows, all columns except last
Y = df.iloc[:, -1].values    # the last column as target                # target

print("X shape:", X.shape)   # (rows, columns)
print("y shape:", y.shape)   # (rows,)


X shape: (4, 4)
y shape: (4,)


In [61]:
np.insert(X,0,1,axis=1)

array([[   1, 2104,    5,    1,   45],
       [   1, 1416,    2,   40,  232],
       [   1, 1534,    3,    2,   30],
       [   1,  852,    2,    1,   36]])

In [62]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)
model = LinearRegression()
model.fit(X_train,y_train)
LinearRegression()
y_pred = model.predict(X_train)


(3, 4)
(1, 4)


In [63]:
model.intercept_


np.float64(-58.7558112584004)

In [64]:
model.coef_

array([ 0.21420258,  0.08802732, -0.13799445,  1.50603203])

In [65]:
y_pred

array([178., 460., 315.])